keys: 
  - &he      age1cz7kkx8w8hxy7qgps20nw7v55963gqz5n53zxy990cv4sj8gjgnqlcz64s
  - &herd    age1n6n0rgcje2q4hl0lsugskx4uy7gcc3pvezkpstypj9kzgw0vu5uqn3hc49
  - &fridge  age1ernaf2t6r8mzem9mquskzv5ncxu2ljz6n4h6xkeqtd2x7lum0uwsqz3sh6
  - &toaster age15xezpvdmckxu895mpxnxpgrmykkrfwrl57z4wac4fgu5axed84qq3sdx7e
creation_rules:
  - path_regex: ^secrets/secrets\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *herd
      - *fridge
      - *toaster
  - path_regex: ^secrets/herd\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *herd
  - path_regex: ^secrets/fridge\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *fridge
  - path_regex: ^secrets/toaster\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *toaster
  - path_regex: ^secrets/hass\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *fridge
  - path_regex: ^secrets/heon\.(yaml|json)$
    key_groups:
    - age:
      - *he
      - *herd
  - path_regex: ^tofu/secrets\.(yaml|json)$
    key_groups:
    - age:
      - *he
