variable tenancy {
  type = string
}

terraform {
  required_providers {
    oci = {
      source = "oracle/oci"
    }
  }
}

## This configuration was generated by terraform-provider-oci

resource "oci_core_dhcp_options" "toaster" {
  compartment_id = var.tenancy
  vcn_id         = oci_core_vcn.toaster.id
  options {
    custom_dns_servers = [
    ]
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    search_domain_names = [
      "vcn04221650.oraclevcn.com"
    ]
    type = "SearchDomain"
  }
}

resource "oci_core_internet_gateway" "toaster" {
  compartment_id = var.tenancy
  vcn_id         = oci_core_vcn.toaster.id
}

resource "oci_core_subnet" "toaster" {
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.tenancy
  vcn_id         = oci_core_vcn.toaster.id
}

resource "oci_core_route_table" "toaster" {
  compartment_id = var.tenancy
  vcn_id         = oci_core_vcn.toaster.id
  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.toaster.id
  }
  route_rules {
    destination       = "::/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.toaster.id
  }
}

resource "oci_core_vcn" "toaster" {
  cidr_blocks    = ["10.0.0.0/16"]
  compartment_id = var.tenancy
}

resource "oci_core_security_list" "toaster" {
  compartment_id = var.tenancy
  vcn_id         = oci_core_vcn.toaster.id
  egress_security_rules {
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    protocol         = "all"
    stateless        = "false"
  }
  egress_security_rules {
    destination      = "::/0"
    destination_type = "CIDR_BLOCK"
    protocol         = "all"
    stateless        = "false"
  }
  freeform_tags = {
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
    }
  }
  ingress_security_rules {
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    description = "http"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
    }
  }
  ingress_security_rules {
    description = "https"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
    }
  }
}

resource "oci_core_private_ip" "toaster" {
  hostname_label = "toaster"
  ip_address     = "10.0.0.216"
  lifetime       = "EPHEMERAL"
  subnet_id      = oci_core_subnet.toaster.id
  vnic_id        = data.oci_core_vnic.toaster.id
}

resource "oci_core_instance" "toaster" {
  agent_config {
    are_all_plugins_disabled = "true"
    is_management_disabled   = "true"
    is_monitoring_disabled   = "true"
  }
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = "MohS:EU-FRANKFURT-1-AD-1"
  compartment_id      = var.tenancy
  create_vnic_details {
    assign_public_ip       = "true"
    display_name           = "toaster"
    hostname_label         = "toaster"
    private_ip             = "10.0.0.216"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.toaster.id
  }
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  shape = "VM.Standard.A1.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "24"
    nvmes                     = "0"
    ocpus                     = "4"
    vcpus                     = "4"
  }
  source_details {
    boot_volume_size_in_gbs = "47"
    boot_volume_vpus_per_gb = "10"
    source_type             = "image"
  }
}

data "oci_core_vnic" "toaster" {
  vnic_id = "ocid1.vnic.oc1.eu-frankfurt-1.abtheljrn6a4m4e5ciq6dtwstfd7pllt7klyacfdwwbrrml6apds4f7i3ofq"
}

output "ipv4" {
  value = data.oci_core_vnic.toaster.public_ip_address
}

output "ipv6" {
  value = data.oci_core_vnic.toaster.ipv6addresses[0]
}
