provider "oci" {
  tenancy_ocid = local.secrets.oci.tenancy
  user_ocid    = local.secrets.oci.user
  private_key  = local.secrets.oci.private_key
  fingerprint  = local.secrets.oci.fingerprint
  region       = local.secrets.oci.region
}

## This configuration was generated by terraform-provider-oci

resource oci_core_dhcp_options export_Default-DHCP-Options-for-vcn-20220725-0021 {
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:57.763Z"
  }
  display_name     = "Default DHCP Options for vcn-20220725-0021"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_vcn-20220725-0021.id
  options {
    custom_dns_servers = [
    ]
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    search_domain_names = [
      "vcn07250024.oraclevcn.com",
    ]
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_Internet-Gateway-vcn-20220725-0021 {
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:58.653Z"
  }
  display_name = "Internet Gateway vcn-20220725-0021"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_vcn-20220725-0021.id
}

resource oci_core_subnet export_subnet-20220725-0021 {
  cidr_block     = "10.0.0.0/24"
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:59.892Z"
  }
  dhcp_options_id = oci_core_dhcp_options.export_Default-DHCP-Options-for-vcn-20220725-0021.id
  display_name    = "subnet-20220725-0021"
  dns_label       = "subnet07250024"
  freeform_tags = {
  }
  ipv6cidr_block = "2603:c020:8007:f222::/64"
  ipv6cidr_blocks = [
    "2603:c020:8007:f222:0000:0000:0000:0000/64",
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_route_table.export_Default-Route-Table-for-vcn-20220725-0021.id
  security_list_ids = [
    oci_core_vcn.export_vcn-20220725-0021.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_vcn-20220725-0021.id
}

resource oci_core_route_table export_Default-Route-Table-for-vcn-20220725-0021 {
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:57.763Z"
  }
  display_name = "Default Route Table for vcn-20220725-0021"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_vcn-20220725-0021.id
  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcn-20220725-0021.id
  }
  route_rules {
    destination       = "::/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-vcn-20220725-0021.id
  }
}

resource oci_core_vcn export_vcn-20220725-0021 {
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:57.763Z"
  }
  display_name = "vcn-20220725-0021"
  dns_label    = "vcn07250024"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  security_attributes = {
  }
}

resource oci_core_security_list export_Default-Security-List-for-vcn-20220725-0021 {
  compartment_id = local.secrets.oci.tenancy
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-24T22:24:57.763Z"
  }
  display_name = "Default Security List for vcn-20220725-0021"
  vcn_id = oci_core_vcn.export_vcn-20220725-0021.id
  egress_security_rules {
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    protocol  = "all"
    stateless = "false"
  }
  egress_security_rules {
    destination      = "::/0"
    destination_type = "CIDR_BLOCK"
    protocol  = "all"
    stateless = "false"
  }
  freeform_tags = {
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
    }
  }
  ingress_security_rules {
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    description = "http"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
    }
  }
  ingress_security_rules {
    description = "https"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
    }
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "::/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
    }
  }
}

resource oci_core_private_ip export_ArmToaster {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-29T10:15:50.508Z"
  }
  display_name = "ArmToaster"
  freeform_tags = {
  }
  hostname_label = "armtoaster"
  ip_address     = "10.0.0.71"
  lifetime       = "EPHEMERAL"
  subnet_id = oci_core_subnet.export_subnet-20220725-0021.id
  vnic_id = "ocid1.vnic.oc1.eu-frankfurt-1.abtheljrz4j66vgz4ghizvjrdqrxjvvfqg6bmet6yu3wafukz7wd2z3krwva"
}

resource oci_core_instance export_toaster {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = "MohS:EU-FRANKFURT-1-AD-1"
  compartment_id = local.secrets.oci.tenancy
  create_vnic_details {
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
      "Oracle-Tags.CreatedOn" = "2022-07-29T10:15:50.508Z"
    }
    display_name = "ArmToaster"
    freeform_tags = {
    }
    hostname_label = "armtoaster"
    nsg_ids = [
    ]
    private_ip = "10.0.0.71"
    security_attributes = {
    }
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_subnet-20220725-0021.id
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/heyi7086@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-07-29T10:15:50.376Z"
  }
  display_name = "toaster"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-3"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  shape = "VM.Standard.A1.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "24"
    nvmes                     = "0"
    ocpus                     = "4"
    vcpus                     = "4"
  }
  source_details {
    boot_volume_size_in_gbs = "64"
    boot_volume_vpus_per_gb = "10"
    source_type = "image"
  }
  state = "RUNNING"
}
